name: Docker Image CI

on: [push]

jobs:
  
  build-upload:
    name: Build Muilti-Platform Image and Upload to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v1

    - name: Build and Upload
      env:
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: |
        # Enable multi-platform builds
        export DOCKER_CLI_EXPERIMENTAL=enabled
        docker run --rm --privileged docker/binfmt:66f9012c56a8316f9244ffd7622d7c21c1f6f28d
        docker buildx create --use --name mybuilder

        # Variables
        TAG=$(date +%y.%m)
        NAME=silentdigit/duckdns
        docker login -u silentdigit -p ${DOCKER_TOKEN}

        # Build image as TAG version
        docker buildx build -t ${NAME}:${TAG} --platform=linux/arm,linux/arm64,linux/amd64 . --push

        # Build image as latest version
        docker buildx build -t ${NAME}:latest --platform=linux/arm,linux/arm64,linux/amd64 . --push
