name: Docker Image CI

on: [push]

jobs:
  
  build-upload:
    name: Build Image and Upload to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v1

    - name: Build and Upload
      env:
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: |
        TAG=$(date +%y.%m)
        docker build --tag silentdigit/duckdns-updater:${TAG} .
        docker login -u silentdigit -p DOCKER_TOKEN
        docker push silentdigit/duckdns-updater:${TAG}
